"""
synthetic_data_generator.py - Realistic Longitudinal Cow Trajectory Simulator
Project: AI/ML-Based Predictive Modelling for Early Forecasting of Bovine Mastitis
PSID: SIH26019

IMPORTANT SCIENTIFIC NOTICE:
This module generates SYNTHETIC longitudinal trajectories for PROTOTYPE DEMONSTRATION ONLY.
Real data (clinical_mastitis_cows.csv) contains only 6-day repeated snapshots with zero onsets.
Every record generated by this module is explicitly tagged with:
data_source = "synthetic_simulation".
"""

import os
import numpy as np
import pandas as pd

np.random.seed(42)


def generate_synthetic_cohort(
    num_cows=200,
    days_per_cow=45,
    incidence_rate=0.35,
    output_path="forecasting/synthetic_longitudinal_cows.csv"
):
    """
    Simulates a longitudinal cohort of cows over a 45-day monitoring window.
    Incorporates empirical distributions from clinical_mastitis_cows.csv:
      - Healthy baseline: IU ~ 190-210, EU ~ 220-245, asymmetry ~ 4-8, temp ~ 38.5-40.5
      - Clinical mastitis: infected quarter jumps +60-100 units, asymmetry jumps to 60-90, temp > 43
      - Subclinical incubation: progressive power-law increase over 14 days before onset.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    all_records = []

    quarters = ['FL', 'FR', 'RL', 'RR']
    num_sick_cows = int(num_cows * incidence_rate)
    sick_cow_indices = set(np.random.choice(range(1, num_cows + 1), size=num_sick_cows, replace=False))

    print(f"Generating synthetic cohort: {num_cows} cows over {days_per_cow} days...")
    print(f"  - Healthy control cows: {num_cows - num_sick_cows}")
    print(f"  - Onset cows (develop mastitis): {num_sick_cows}")

    for cow_num in range(1, num_cows + 1):
        cow_id = f"synth_cow_{cow_num:03d}"
        is_sick_cow = cow_num in sick_cow_indices

        breed = np.random.choice(['Jersey', 'hostlene'], p=[0.95, 0.05])
        months_after_birth = int(np.random.choice([1, 2, 3, 4, 5, 6], p=[0.20, 0.20, 0.18, 0.16, 0.14, 0.12]))
        prev_mastitis = 1 if np.random.rand() < 0.08 else 0

        base_iu = np.random.normal(195.0, 15.0)
        base_iu = np.clip(base_iu, 160.0, 230.0)
        q_iu_base = {q: base_iu + np.random.normal(0, 2.0) for q in quarters}

        diff_base = np.random.normal(34.0, 3.0)
        q_eu_base = {q: q_iu_base[q] + diff_base + np.random.normal(0, 1.5) for q in quarters}
        base_temp = np.random.normal(39.0, 0.5)

        if is_sick_cow:
            onset_day = int(np.random.randint(22, 38))
            infected_quarter = np.random.choice(quarters)
            second_infected_q = np.random.choice([q for q in quarters if q != infected_quarter]) if np.random.rand() < 0.20 else None
        else:
            onset_day = None
            infected_quarter = None
            second_infected_q = None

        for day in range(1, days_per_cow + 1):
            if is_sick_cow:
                days_to_onset = day - onset_day
                is_clinical = (day >= onset_day)
            else:
                days_to_onset = 999
                is_clinical = False

            day_noise_iu = {q: np.random.normal(0, 1.5) for q in quarters}
            day_noise_temp = np.random.normal(0, 0.20)

            iu_elevation = {q: 0.0 for q in quarters}
            temp_elevation = 0.0
            diff_elevation = 0.0

            if is_sick_cow:
                if days_to_onset < -14:
                    pass
                elif -14 <= days_to_onset < 0:
                    # Biological power-law incubation progression over 14 days
                    t_prog = (days_to_onset + 14) / 14.0  # 0.0 at Day -14 -> 1.0 at Day 0
                    progression_factor = (t_prog) ** 1.8

                    iu_elevation[infected_quarter] = 75.0 * progression_factor
                    if second_infected_q:
                        iu_elevation[second_infected_q] = 45.0 * progression_factor
                    temp_elevation = 3.8 * progression_factor
                    diff_elevation = 10.0 * progression_factor

                else:
                    # Active Clinical Mastitis (Day 0 onwards)
                    iu_elevation[infected_quarter] = np.random.normal(85.0, 4.0)
                    if second_infected_q:
                        iu_elevation[second_infected_q] = np.random.normal(55.0, 3.0)
                    temp_elevation = np.random.normal(4.5, 0.4)
                    diff_elevation = np.random.normal(14.0, 1.5)

            # Non-mastitic transient heat stress simulation for healthy cows
            if not is_sick_cow and cow_num % 15 == 0 and 18 <= day <= 21:
                temp_elevation = 2.0
                for q in quarters:
                    iu_elevation[q] = 8.0

            curr_iu = {}
            curr_eu = {}
            for q in quarters:
                curr_iu[q] = q_iu_base[q] + iu_elevation[q] + day_noise_iu[q]
                curr_eu[q] = q_eu_base[q] + iu_elevation[q] + diff_elevation + day_noise_iu[q] * 1.1

            curr_temp = base_temp + temp_elevation + day_noise_temp

            if is_clinical:
                milk_visibility = 1
                hardness = 1 if np.random.rand() < 0.85 else 0
                pain = 1 if np.random.rand() < 0.70 else 0
                class1 = 1
            else:
                milk_visibility = 0
                hardness = 0
                pain = 0
                class1 = 0

            target_onset_7_14d = 1 if (is_sick_cow and (7 <= (onset_day - day) <= 14)) else 0
            target_onset_next_14d = 1 if (is_sick_cow and (1 <= (onset_day - day) <= 14)) else 0
            target_onset_next_1_6d = 1 if (is_sick_cow and (1 <= (onset_day - day) <= 6)) else 0

            record = {
                'data_source': "synthetic_simulation",
                'Cow_ID': cow_id,
                'Day': day,
                'Breed': breed,
                'Months after giving birth': months_after_birth,
                'Previous_Mastits_status': prev_mastitis,
                'IUFL': round(curr_iu['FL'], 1),
                'EUFL': round(curr_eu['FL'], 1),
                'IUFR': round(curr_iu['FR'], 1),
                'EUFR': round(curr_eu['FR'], 1),
                'IURL': round(curr_iu['RL'], 1),
                'EURL': round(curr_eu['RL'], 1),
                'IURR': round(curr_iu['RR'], 1),
                'EURR': round(curr_eu['RR'], 1),
                'Temperature': round(curr_temp, 1),
                'Hardness': hardness,
                'Pain': pain,
                'Milk_visibility': milk_visibility,
                'class1': class1,
                'is_sick_cow': int(is_sick_cow),
                'onset_day': onset_day if onset_day is not None else -1,
                'days_to_onset': days_to_onset,
                'is_clinical_active': int(is_clinical),
                'target_onset_7_14d': target_onset_7_14d,
                'target_onset_next_14d': target_onset_next_14d,
                'target_onset_next_1_6d': target_onset_next_1_6d
            }
            all_records.append(record)

    df_synth = pd.DataFrame(all_records)
    df_synth.to_csv(output_path, index=False)
    print(f"Generated synthetic longitudinal dataset with shape: {df_synth.shape}")
    print(f"Saved to: {output_path}")

    return df_synth


if __name__ == "__main__":
    generate_synthetic_cohort()
